### ISSUE TITLE
Multiple Icon problems

### ISSUE THREAD

**Issue by Unknow0059** [Deytron/SteamNite#13]
![%pn_J8H_050420-01h40m31s](https://user-images.githubusercontent.com/25656892/80936627-5ba84d00-8da8-11ea-8f64-bf2d4601456f.png)
![image](https://user-images.githubusercontent.com/25656892/80936698-a4f89c80-8da8-11ea-935c-c9bfbdbeefce.png) Missing Grid View Detail icon

My screen resolution is 1366×768.

Issue 3 is not present in Details View.

**Comment by Deytron** [comment]
Only a complete redesign of the theme for sub-1080p screens will fix those issues. I've been working on it but left it on the side to update another theme. I will get back at it later. As for the icons missing, it's the very first time I see that, as on another screen with a resolution of 1366x768 they appear fine. There seems to be an issue with Unicode on your end

**Comment by Unknow0059** [comment]
I'm not sure how I would fix that. I haven't modified your theme.

**Comment by Unknow0059** [comment]
I sat on it for a bit. I think it could be related to my non-default Windows font. I use a monospace one.

I didn't consider this at first because I assumed the characters were images.

Guess that means the issue should be closed, because it is now a Windows 10 issue. Changing the default font makes some characters display strangely in certain areas of File Explorer, too.

**Comment by McCovican** [comment]
I'm having the same issue as in point #1 - the overlapping filter and clear buttons. I'm using Playnite maximised on a 1080p display in win7.

![200505143820](https://user-images.githubusercontent.com/11760565/81072538-3158ab80-8ede-11ea-85f4-2b2d40c38386.png)
