### ISSUE TITLE
Play and info icons on game covers in grid mode barely visible on not darkened games

### ISSUE THREAD

**Issue by darklinkpower** [Deytron/SteamNite#15]
Not darkened
![imagen](https://user-images.githubusercontent.com/1389286/81460777-1d76a900-916d-11ea-96b6-1575120ba1d2.png)

Darkened. Icons can be seen:
![imagen](https://user-images.githubusercontent.com/1389286/81460793-37b08700-916d-11ea-98dd-efac9d0f48b2.png)

**Comment by Deytron** [comment]
The Steam client exhibits the same behavior
![image](https://user-images.githubusercontent.com/20344764/81480374-b0751900-9229-11ea-8ce2-d1386ac2e35f.png)
Obviously I'll edit the theme to make the icons more obvious, as it's better anyway

**Comment by darklinkpower** [comment]
I agree, I checked just to see steam behaviour but I saw they didn't make adjustment here so I didn't make a Steam comparison. Such a shame they didn't do it
