### ISSUE TITLE
Blur Bar that partially covers background image has a gap between it and details

### ISSUE THREAD

**Issue by darklinkpower** [Deytron/SteamNite#2]
There's a gap
![imagen](https://user-images.githubusercontent.com/1389286/79276420-9552fb80-7e6d-11ea-8b5b-f3980be60d15.png)

Zoom:
![imagen](https://user-images.githubusercontent.com/1389286/79276272-591f9b00-7e6d-11ea-90f6-e79bcb1c02c4.png)

This is on a 1920x1080 screen and 100% DPI

**Comment by Deytron** [comment]
Ok, so I identified the issue. If the hero is not with an aspect ratio of exactly 3:1, the image gets a bit too far.

![image](https://user-images.githubusercontent.com/20344764/79320080-7bff8d00-7f09-11ea-9be9-2b8e0d5a0a10.png)

It should be a simple fix.
