### ISSUE TITLE
Integration with SuccessStory / Statistics

### ISSUE THREAD

**Issue by shakeyourbunny** [Deytron/SteamNite#22]
An integration of Lacro59's Success Story and Statistics would be really neat.

**Comment by Lacro59** [comment]
:'(
I' m not Lero59 :p

**Comment by darklinkpower** [comment]
lol

**Comment by shakeyourbunny** [comment]
Well, I edited. At the time of writing of the issue, I was  too lazy to look up the exact name. 

Anyways, I'd really be happy to have integration for @Lacro59 's extensions here :)

**Comment by FF7CloudsNobody** [comment]
> Well, I edited. At the time of writing of the issue, I was too lazy to look up the exact name.
> 
> Anyways, I'd really be happy to have integration for @Lacro59 's extensions here :)

I made a pull request, decided to add it in myself and it looks similar to Steam's Achievement progress bar. If it isn't processed then I may end up making a "SteamierNite" theme with extra edits to make it more in line with Steam's setup.

**Comment by Deytron** [comment]
Big thanks to @FF7CloudsNobody for integrating Success Stories to SteamNite and making the description collapsible ! I'll edit the theme properly and fix everything when Playnite 8 will be out on the 14th of October.
