### ISSUE TITLE
Use "Icon height" value in settings for details view

### ISSUE THREAD

**Issue by darklinkpower** [Deytron/SteamNite#29]
Currently the icon (Or logo) size seems to be hard-coded. Ideally it should be configurable using the settings in Playnite.

It also would help for people who use icons normally, since generally icons are very low resolution and pixellate a lot when they are bigger.

![imagen](https://user-images.githubusercontent.com/1389286/94995494-3e002f00-0564-11eb-9f26-228720ac176a.png)

**Comment by Deytron** [comment]
It seems you are mistaken on that one. The Icon Height value changes the height of the icons on the side list, not the logo. I absolutely can make it so it changes the height of the logo, but there's only one option for two images, so I'm gonna have to make a choice. Which is more pertinent ?

- To let the "ICon height" value change the logo height and hardcode the icons sizes' in the game list ?
- To leave it as is, with a hardcoded logo height ?

Either option is good.

**Comment by darklinkpower** [comment]
That's true, I misremembered because I thought there was a similar setting like the cover size in details view where you can set the height.

In my opinion I would keep it as it is (option 2) to have the intended behaviour of the setting.

**Comment by Deytron** [comment]
Alright, leaving it as is
