### ISSUE TITLE
No scrollbar in details view

### ISSUE THREAD

**Issue by darklinkpower** [Deytron/SteamNite#32]
![imagen](https://user-images.githubusercontent.com/1389286/97644814-ea70ec00-1a10-11eb-84d9-0ec43c1a9963.png)

**Comment by Deytron** [comment]
That one is a voluntary change. I don't like having a big scrollbar on the right takins some space. I agree that leaving it visible would make it match Steam, but I don't know.

**Comment by darklinkpower** [comment]
More than an aesthetic issue here, the problem is that it makes it difficult to scroll up and down, more so when using the touchpad of a laptop.

**Comment by Deytron** [comment]
Alright, I'll make it visible
