### ISSUE TITLE
Hover color in details and list view not the same as Steam

### ISSUE THREAD

**Issue by darklinkpower** [Deytron/SteamNite#35]
Steamnite

![imagen](https://user-images.githubusercontent.com/1389286/97646042-32454280-1a14-11eb-904a-7639648d9c5e.png)

Steam

![imagen](https://user-images.githubusercontent.com/1389286/97646050-3a04e700-1a14-11eb-8279-5fb91888e2d7.png)

Selected is a little different too but don't know if it's necessary to change too

**Comment by Deytron** [comment]
Here's how mine looks like in Steam 
![image](https://user-images.githubusercontent.com/20344764/97699558-a0d4df80-1aaa-11eb-8e97-35c6a24e996c.png)

**Comment by darklinkpower** [comment]
There's an issue with Steam that when enabling or disabling GPU acceleration will change the colors. If I disable GPU acceleration my colors look like yours. It will depend in what colors you prefer in this case, personally I prefer the cotrast of the GPU disabled version.

Also upon closer look, both the selected and highlight colors don't match with neither your colors/GPU disabled or what I showed first. Steam used more dark-blue colors.

![imagen](https://user-images.githubusercontent.com/1389286/97745218-24dc9680-1aae-11eb-895f-8cdab869ffd1.png)

![imagen](https://user-images.githubusercontent.com/1389286/97745724-eabfc480-1aae-11eb-81bd-cd5d3a2bccdb.png)

**Comment by Deytron** [comment]
Huh. That's all very strange, because I do have GPU acceleration enabled but I did not do anything to colors on my screen.
I'll keep the colors used when GPU accel is enabled in Steam, as it is enabled by default in the client.

**Comment by darklinkpower** [comment]
My guess is it only happens with certain GPUs, I doubt the color change is an intended change.
