### ISSUE TITLE
Suggestion to add separators to panels to make it consistent

### ISSUE THREAD

**Issue by darklinkpower** [Deytron/SteamNite#36]
Steam uses a small separator in the game list
![imagen](https://user-images.githubusercontent.com/1389286/97646174-a5e74f80-1a14-11eb-9a91-f88dd0efde97.png)

Same for Steamnite
![imagen](https://user-images.githubusercontent.com/1389286/97646210-bbf51000-1a14-11eb-9783-2c8eb27801cc.png)

I think it would be a good idea to add separators to the filter and explorer panels to make it consistent
![imagen](https://user-images.githubusercontent.com/1389286/97646311-f199f900-1a14-11eb-9d27-5e316e576d6a.png)

**Comment by Deytron** [comment]
There's now a 2 pixels line for separators
