### ISSUE TITLE
Make current version with details at the bottom an alternative version

### ISSUE THREAD

**Issue by darklinkpower** [Deytron/SteamNite#38]
The details in the bottom of grid view don't make much sense to me for the following reasons

1. Duplicate information is shown in the same view
![imagen](https://user-images.githubusercontent.com/1389286/97649327-a97ed480-1a1c-11eb-89f6-b368ba95f1f9.png)

2. Information size is inconsistent to fit different sized strings
![imagen](https://user-images.githubusercontent.com/1389286/97649658-7721a700-1a1d-11eb-8d3c-b1fa5806efb6.png)
![imagen](https://user-images.githubusercontent.com/1389286/97650412-388cec00-1a1f-11eb-87d5-efe0579ee2fd.png)

3. Related to the previous point, you can only fit a little information due to the available area

4. Personal opinion but I think it saturates the UI and worsens the general look.

In my opinion a version with this details section should be offered as an alternative version and the normal version be the one without it.

**Comment by Deytron** [comment]
Yup, I can do that.
