### ISSUE TITLE
Gear and information icons are blurry

### ISSUE THREAD

**Issue by darklinkpower** [Deytron/SteamNite#39]
These two are the only icons that are blurry in the theme

Details view

![imagen](https://user-images.githubusercontent.com/1389286/97651897-dd5cf880-1a22-11eb-95c9-3e9f99d83cfd.png)

Grid View

![imagen](https://user-images.githubusercontent.com/1389286/97651924-ef3e9b80-1a22-11eb-8b85-6743860b5d24.png)

![imagen](https://user-images.githubusercontent.com/1389286/97651963-fcf42100-1a22-11eb-8c89-2948599b033d.png)

**Comment by Deytron** [comment]
So I just went brute force and upscaled them 5 times. Only takes a couple kilobytes.
