### ISSUE TITLE
Change right click menu colors to match Steam

### ISSUE THREAD

**Issue by darklinkpower** [Deytron/SteamNite#40]
Steamnite on the left. Steam on the right (Darker gray). The separator also uses white/gray instead of the blue in Steamnite.

![imagen](https://user-images.githubusercontent.com/1389286/97652404-e1d5e100-1a23-11eb-8232-65bba96ff97c.png)

**Comment by Deytron** [comment]
So I can change the background color, but I couldn't change the separator colors. Either I couldn't find it in all the constants or it is hardcoded
