### ISSUE TITLE
Remove borders in selection and check boxes to match Steam UI

### ISSUE THREAD

**Issue by darklinkpower** [Deytron/SteamNite#42]
Steam uses a clean look doesn't have borders in the new library UI. The boxes background color would also be needed to be changed to a dark gray.

Examples:
![imagen](https://user-images.githubusercontent.com/1389286/97653344-28c4d600-1a26-11eb-9900-2e33ceecdc1c.png)
![imagen](https://user-images.githubusercontent.com/1389286/97653397-514cd000-1a26-11eb-88a2-6d10316b6b49.png)
![imagen](https://user-images.githubusercontent.com/1389286/97653477-822d0500-1a26-11eb-940c-07ca4305fa19.png)

Steamnite currently uses boxes with blue borders
![imagen](https://user-images.githubusercontent.com/1389286/97653521-97099880-1a26-11eb-950b-ae7992963fe6.png)
![imagen](https://user-images.githubusercontent.com/1389286/97653532-9f61d380-1a26-11eb-8f7e-702ce01bd0de.png)
![imagen](https://user-images.githubusercontent.com/1389286/97653552-a7ba0e80-1a26-11eb-9918-0aa6f73fdc97.png)

**Comment by Deytron** [comment]
So I managed to make it clean, but this also removes border from checkboxes.
![image](https://user-images.githubusercontent.com/20344764/97720940-25cef180-1ac9-11eb-9671-a79bcb6b915d.png)
![image](https://user-images.githubusercontent.com/20344764/97720894-1780d580-1ac9-11eb-92f0-3cec048fe25c.png)
They obvisouly still work, but I don't know which is better

**Comment by darklinkpower** [comment]
Removing the borders from checkboxes is what steam does too.

![imagen](https://user-images.githubusercontent.com/1389286/97746726-7554f380-1ab0-11eb-9705-fef2c1ce7ea0.png)

The thing needed would be to change the window background color to the light gray to give the contrast.

Also not sure if it would be possible to the boxes darken a little when hovered.
![dtgOnnmBvP](https://user-images.githubusercontent.com/1389286/97746832-a2a1a180-1ab0-11eb-879d-3830cc30d077.gif)

![imagen](https://user-images.githubusercontent.com/1389286/97748605-5310a500-1ab3-11eb-9647-959f293282d0.png)

![imagen](https://user-images.githubusercontent.com/1389286/97748400-0f1da000-1ab3-11eb-8547-beed1c2e2f09.png)

**Comment by Deytron** [comment]
Alriight, I managed to make it so the checkboxes have a background color.
