### ISSUE TITLE
Change button brightness on hover

### ISSUE THREAD

**Issue by darklinkpower** [Deytron/SteamNite#43]
Small detail but one that improves the UI. The squares change brightness.

In Steamnite:
![iqkXEF7zln](https://user-images.githubusercontent.com/1389286/97653877-6a09b580-1a27-11eb-8aa4-0c03ea92cccc.gif)

In Steam:
![Ia24kweLps](https://user-images.githubusercontent.com/1389286/97653899-74c44a80-1a27-11eb-9e9b-e231b9370c2b.gif)

**Comment by Deytron** [comment]
It looks like I can't make it like that, the trigger will only change the background

**Comment by Deytron** [comment]
Nevermind, managed to fix it thanks to your help
