### ISSUE TITLE
Suggestion: add missing buttons to match steam UI and add missing features

### ISSUE THREAD

**Issue by darklinkpower** [Deytron/SteamNite#6]
Missing buttons:
![imagen](https://user-images.githubusercontent.com/1389286/79277853-3ba00080-7e70-11ea-8be7-2c996876604d.png)

It could be great if the theme had the same "Favorite button"

For the "Manage" button it could open the Edit window, the one opened by this button on the default Playnite theme
![imagen](https://user-images.githubusercontent.com/1389286/79278029-8d488b00-7e70-11ea-9516-089530434d5e.png)

**Comment by Deytron** [comment]
The favorite button is not possible for now. Will add it in a future version of Playnite
